/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/MyDatabase": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["MyTable"])[];
            "application/json": (components["schemas"]["MyTable"])[];
            "text/json": (components["schemas"]["MyTable"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MyTable"];
          "text/json": components["schemas"]["MyTable"];
          "application/*+json": components["schemas"]["MyTable"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MyTable"];
            "application/json": components["schemas"]["MyTable"];
            "text/json": components["schemas"]["MyTable"];
          };
        };
      };
    };
  };
  "/api/MyDatabase/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MyTable"];
            "application/json": components["schemas"]["MyTable"];
            "text/json": components["schemas"]["MyTable"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MyTable"];
          "text/json": components["schemas"]["MyTable"];
          "application/*+json": components["schemas"]["MyTable"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    MyTable: {
      /** Format: int64 */
      id?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
