/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/MyDatabase": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["MyTable"])[];
            "application/json": (components["schemas"]["MyTable"])[];
            "text/json": (components["schemas"]["MyTable"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MyTable"];
          "text/json": components["schemas"]["MyTable"];
          "application/*+json": components["schemas"]["MyTable"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MyTable"];
            "application/json": components["schemas"]["MyTable"];
            "text/json": components["schemas"]["MyTable"];
          };
        };
      };
    };
  };
  "/api/MyDatabase/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["MyTable"];
            "application/json": components["schemas"]["MyTable"];
            "text/json": components["schemas"]["MyTable"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MyTable"];
          "text/json": components["schemas"]["MyTable"];
          "application/*+json": components["schemas"]["MyTable"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Person": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["Person"])[];
            "application/json": (components["schemas"]["Person"])[];
            "text/json": (components["schemas"]["Person"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Person"];
          "text/json": components["schemas"]["Person"];
          "application/*+json": components["schemas"]["Person"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Person"];
            "application/json": components["schemas"]["Person"];
            "text/json": components["schemas"]["Person"];
          };
        };
      };
    };
  };
  "/api/Person/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Person"];
            "application/json": components["schemas"]["Person"];
            "text/json": components["schemas"]["Person"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Person"];
          "text/json": components["schemas"]["Person"];
          "application/*+json": components["schemas"]["Person"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Person/{id}/movies": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["Title"])[];
            "application/json": (components["schemas"]["Title"])[];
            "text/json": (components["schemas"]["Title"])[];
          };
        };
      };
    };
  };
  "/api/Rating": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["Rating"])[];
            "application/json": (components["schemas"]["Rating"])[];
            "text/json": (components["schemas"]["Rating"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Rating"];
          "text/json": components["schemas"]["Rating"];
          "application/*+json": components["schemas"]["Rating"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Rating"];
            "application/json": components["schemas"]["Rating"];
            "text/json": components["schemas"]["Rating"];
          };
        };
      };
    };
  };
  "/api/Rating/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Rating"];
            "application/json": components["schemas"]["Rating"];
            "text/json": components["schemas"]["Rating"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Rating"];
          "text/json": components["schemas"]["Rating"];
          "application/*+json": components["schemas"]["Rating"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Title": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["Title"])[];
            "application/json": (components["schemas"]["Title"])[];
            "text/json": (components["schemas"]["Title"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Title"];
          "text/json": components["schemas"]["Title"];
          "application/*+json": components["schemas"]["Title"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Title"];
            "application/json": components["schemas"]["Title"];
            "text/json": components["schemas"]["Title"];
          };
        };
      };
    };
  };
  "/api/Title/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Title"];
            "application/json": components["schemas"]["Title"];
            "text/json": components["schemas"]["Title"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Title"];
          "text/json": components["schemas"]["Title"];
          "application/*+json": components["schemas"]["Title"];
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/api/Title/search/{searchString}": {
    get: {
      parameters: {
        path: {
          searchString: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["Title"])[];
            "application/json": (components["schemas"]["Title"])[];
            "text/json": (components["schemas"]["Title"])[];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    MyTable: {
      /** Format: int64 */
      id?: number;
      name?: string | null;
    };
    Person: {
      personId?: string | null;
      name?: string | null;
      /** Format: int64 */
      born?: number | null;
      /** Format: int64 */
      died?: number | null;
    };
    Rating: {
      titleId?: string | null;
      /** Format: int64 */
      rating1?: number | null;
      /** Format: int64 */
      votes?: number | null;
    };
    Title: {
      titleId?: string | null;
      type?: string | null;
      primaryTitle?: string | null;
      originalTitle?: string | null;
      /** Format: int64 */
      isAdult?: number | null;
      /** Format: int64 */
      premiered?: number | null;
      /** Format: int64 */
      ended?: number | null;
      /** Format: int64 */
      runtimeMinutes?: number | null;
      genres?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
